from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('help/', views.help_page, name='help'),
    path('categories/', views.CategoryListView.as_view(), name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('threads/', views.ThreadListView.as_view(), name='threads'),
    path('thread/<int:pk>', views.ThreadDetailView.as_view(), name='thread-detail'),
    path('thread/new/', views.ThreadCreateView.as_view(), name='thread-create'),
    path('profile/<int:pk>', views.UserProfileDetailView.as_view(), name='profile-detail'),
    path('profile/<int:pk>/edit/', views.UserProfileUpdateView.as_view(), name='profile-edit'),
    path('api/time/', views.time_proxy, name='time-proxy'),
    path('users/', views.UserListView.as_view(), name='users'),
    path('my-posts/', views.MyPostsListView.as_view(), name='my-posts'),
    path('post/new/', views.PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/edit/', views.PostUpdateView.as_view(), name='post-edit'),
    path('post/<int:pk>/delete/', views.PostDeleteView.as_view(), name='post-delete'),
    path('post/bulk-delete/', views.post_bulk_delete, name='post-bulk-delete'),
    path('search/', views.thread_search, name='thread-search'),
    path('register/step1/', views.register_step1, name='register-step1'),
    path('register/step2/', views.register_step2, name='register-step2'),
    path('register/skip/', views.register_skip, name='register-skip'),
    path('toggle-dark-mode/', views.toggle_dark_mode, name='toggle-dark-mode'),
    # Notification URLs
    path('notifications/', views.NotificationListView.as_view(), name='notifications'),
    path('notifications/mark-read/<int:pk>/', views.notification_mark_read, name='notification-mark-read'),
    path('notifications/mark-all-read/', views.notification_mark_all_read, name='notification-mark-all-read'),
    # AI Summarize
    path('thread/<int:pk>/summarize/', views.summarize_thread, name='thread-summarize'),
    # Moderator URLs
    path('moderator/', views.ModeratorDashboardView.as_view(), name='moderator-dashboard'),
    path('moderator/posts/', views.ModeratorPostListView.as_view(), name='moderator-posts'),
    path('moderator/post/<int:pk>/delete/', views.ModeratorPostDeleteView.as_view(), name='moderator-post-delete'),
    path('moderator/bulk-delete/', views.moderator_bulk_delete, name='moderator-bulk-delete'),
    # Staff URLs
    path('staff/', views.StaffDashboardView.as_view(), name='staff-dashboard'),
    path('staff/users/', views.StaffUserListView.as_view(), name='staff-users'),
    path('staff/user/<int:pk>/delete/', views.StaffUserDeleteView.as_view(), name='staff-user-delete'),
    path('staff/bulk-delete-users/', views.staff_bulk_delete_users, name='staff-bulk-delete-users'),
    path('staff/categories/', views.StaffCategoryListView.as_view(), name='staff-categories'),
    path('staff/category/<int:pk>/delete/', views.StaffCategoryDeleteView.as_view(), name='staff-category-delete'),
    path('staff/bulk-delete-categories/', views.staff_bulk_delete_categories, name='staff-bulk-delete-categories'),
    path('staff/threads/', views.StaffThreadListView.as_view(), name='staff-threads'),
    path('staff/thread/<int:pk>/delete/', views.StaffThreadDeleteView.as_view(), name='staff-thread-delete'),
    path('staff/bulk-delete-threads/', views.staff_bulk_delete_threads, name='staff-bulk-delete-threads'),
    # Like URLs
    path('post/<int:pk>/like/', views.toggle_like_post, name='post-like'),
]