# Generated by Django 5.2.7 on 2025-11-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-is_pinned', '-updated_date'], 'permissions': (('can_moderate_thread', 'Can view all threads and moderate'),)},
        ),
    ]
