# Generated by Django 5.2.7 on 2025-12-03 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_userprofile_dark_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_post', 'New Post in Thread')], default='new_post', max_length=20)),
                ('message', models.CharField(help_text='Notification message text', max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(help_text='The post that triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='catalog.post')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_date'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='catalog_not_recipie_507b8b_idx'), models.Index(fields=['recipient', '-created_date'], name='catalog_not_recipie_d4251f_idx')],
            },
        ),
    ]
