# Generated by Django 5.2.7 on 2025-12-03 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_add_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False, help_text='User is a moderator'),
        ),
    ]
